# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Runs a single command using the runners shell
      - name: Set executable for run.sh
        run: chmod +x run.sh
      - name: Run
        run: ./run.sh
      - name: Update change README.md
        uses: EndBug/add-and-commit@v6
        with:
          author_name: vleedev
          author_email: me@vlee.dev
          message: 'update README.md by CI'
          add: 'README.md'
      - name: Update all txt files in cache
        uses: EndBug/add-and-commit@v6
        with:
          author_name: vleedev
          author_email: me@vlee.dev
          message: 'make unique by CI'
          add: 'cache/*.txt'
