# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u "${GITHUB_ACTOR}" --password-stdin
      # Runs a single command using the runners shell
      - name: Set executable for run.sh
        run: chmod +x run.sh
      - name: Run
        run: ./run.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v6
        with:
          author_name: vleedev
          author_email: me@vlee.dev
          message: 'Update README.md'
          add: 'README.md'
